# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BaseFramesDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BaseFramesDemo
  pod 'Masonry', '~> 1.1.0'
  #pod 'ConvenienceKitHaris', '~> 0.1.0'
  #开源库本地直接映射库
  pod 'ConvenienceKitHaris', :path => '~/Desktop/CustomKit/ConvenienceKitHaris'


end
